- name: Apt update
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Full upgrade
  ansible.builtin.apt:
    upgrade: full

- name: Install all the packages neeeded using apt
  ansible.builtin.apt:
    pkg: "{{ package_needed }}"
    state: present

- name: Upgrade all packages (safe upgrade)
  ansible.builtin.apt:
    upgrade: yes

- name: Remove compilers (gcc, make)
  ansible.builtin.apt:
    pkg: "{{ package_to_remove }}"
    state: absent

- name: Disable systemd-binfmt service
  systemd:
    name: systemd-binfmt
    enabled: no
    state: stopped
  tags:
  - molecule-idempotence-notest