- name: Configure systemd resolved
  become: true
  ansible.builtin.template:
    src: "resolved.conf.j2"
    dest: /etc/systemd/resolved.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  notify: Reload systemd

- name: Restart resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  tags:
  - molecule-idempotence-notest
